/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:83c2096d-34e9-4ba4-9d56-877ce626bcdd",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_6mzSMOOzE",
    "aws_user_pools_web_client_id": "6vs1q8pg7am22p8arfsqo27emi",
    "oauth": {
        "domain": "obsydian-stage.auth.ap-southeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://obsydian.com.au/",
        "redirectSignOut": "https://obsydian.com.au/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "obsydianb197df0c00754029af0ed78f8b9e5d6a141039-stage",
    "aws_user_files_s3_bucket_region": "ap-southeast-2"
};


export default awsmobile;
